### ISSUE TITLE
关于Make的一些问题

### ISSUE THREAD

**Issue by alex-huang-real** [Vizdl/linux-lib#1]
作者你好，我用你的脚本去执行Linux2.6.24的源码出现了问题，但执行Linux2.6.34的源码却是可以的。你的脚本对源码版本有要求的吗？

**Comment by Vizdl** [comment]
Linux版本之间对应的编译器版本和一些环境会不太一样，特别是早期版本，之前的版本是只能针对2.6.34版本。
